### ISSUE TITLE
minifyt the files

### ISSUE THREAD

**Issue by dev-schaffer** [WeRWebAliens/portfolio#13]
download the files and bind them as minfyt scripts in your header
this files:
`<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<link href="https://fonts.googleapis.com/css?family=Revalia" rel="stylesheet">`
*so we can achieve faster loading times

**Comment by Mildred14** [comment]
Hi @dev-schaffer  I can help you with this
